### ISSUE TITLE
Elemental Icons

### ISSUE THREAD

**Issue by BeerMC** [Arasple/TrMenuPro#8]
**希望可以支持补全某些参数的功能**
比如command: tpa @choose_online_player@
会向玩家弹出一个箱子界面，里面是在线玩家头像，点击其中一个，自动补全指令中的玩家名并执行。
这样的功能也可以拓展，比如
@choose_a_number_A_B@，选一个A至B范围的数字

**Comment by Arasple** [comment]
I will do everything I can to achieve this feature with multiple pages support

```YAML
Icons:
   ExampleIcon:
         name: '&7Player Name {element.name}'
         lore: '&3Level: {element.level}'
         list:
           collection: 'bukkitServer.getOnlinePlayers()'
           sortBy: 'player.getName()'
           filter: 'player.hasPermission("perm")'
           elements:
             name: 'element.getName()'
             level: 'element.getLevel()'

```
